### ISSUE TITLE
[BUG] Barcode scanner does not find matches in local database when UPC begins in zero

### ISSUE THREAD

**Issue by terminalmage** [davidhealey/waistline#867] opened 2024-10-31 03:53 UTC
Sometimes the values returned in a scan are inaccurate, and I have to correct them when saving to my local database. However, after saving locally, scanning still only searches the internet. It would be nice to be able to match the locally-saved values with matching UPC codes.

**Comment by EmilJunker** [comment] 2024-10-31 05:09
I don't understand your request. The barcode scanner already prioritizes the local database over searching online. If the item you scanned exists in your local database, Waistline will take you to it. This even works while you are offline.

**Comment by terminalmage** [comment] 2024-11-07 01:13
That is simply not true.

1. On the "Diary" view, tap the + icon next to the appropriate meal.
1. Tap the barcode icon
1. Scan the item

When the above steps are followed, the scanner takes you to an "Add new item" screen with the (incorrect) values from Open Food Facts.

**Comment by terminalmage** [comment] 2024-11-07 01:17
Furthermore, when I use the barcode scanner with wifi and mobile data, I get a "No Internet Connection" error.

**Comment by EmilJunker** [comment] 2024-11-07 05:08
@terminalmage You must be using an outdated version then. The latest version is 3.8.0. Please update the app and try it again. All the things you complain about have been addressed in the latest version.

**Comment by terminalmage** [comment] 2024-11-07 21:42
I have only ever used 3.8.0.

**Comment by EmilJunker** [comment] 2024-11-07 22:08
> I tried backing up the database to take a look, but the backup is saved to /Android/data which is inaccessible in Android 14

You should be able to access the backup folder using this file browser app from the Play Store:
https://play.google.com/store/apps/details?id=com.marc.files

**Comment by terminalmage** [comment] 2024-11-08 00:05
> > When the above steps are followed, the scanner takes you to an "Add new item" screen with the (incorrect) values from Open Food Facts.
> 
> > Furthermore, when I use the barcode scanner with wifi and mobile data both disabled, I get a "No Internet Connection" error.
> 
> > I have only ever used 3.8.0.
> 
> If that's the case, there is only one possible explanation: The item you are scanning does not exist in your local database. If there was an entry in your local database with the same barcode as the one you scanned, Waistline would take you to it and there would be no need for an internet connection.
> 

There literally is not _only one_ possible explanation. Because I've found the bug.

The item is identified and added to the selection _only when the UPC begins with a non-zero digit_. Every single thing I have scanned to this point has started with a zero, and none of them work. I just scanned an item with a UPC beginning in 4 and it worked as it's supposed to. I've actually now scanned two items beginning in zero and they both work.

**Comment by davidhealey** [comment] 2024-11-08 00:07
> Every single thing I have scanned to this point has started with a zero, and none of them work.

In what way did they not work?

**Comment by terminalmage** [comment] 2024-11-08 00:07
> > Every single thing I have scanned to this point has started with a zero, and none of them work.
> 
> In what way did they not work?

https://github.com/davidhealey/waistline/issues/867#issuecomment-2461119065

**Comment by davidhealey** [comment] 2024-11-08 00:08
> > > Every single thing I have scanned to this point has started with a zero, and none of them work.
> > 
> > 
> > In what way did they not work?
> 
> [#867 (comment)](https://github.com/davidhealey/waistline/issues/867#issuecomment-2461119065)

So these are items that are already in your foodlist and show a barcode in the food editor window?

**Comment by terminalmage** [comment] 2024-11-08 00:09
> > > > Every single thing I have scanned to this point has started with a zero, and none of them work.
> > > 
> > > 
> > > In what way did they not work?
> > 
> > 
> > [#867 (comment)](https://github.com/davidhealey/waistline/issues/867#issuecomment-2461119065)
> 
> So these are items that are already in your foodlist and show a barcode in the food editor window?

Yes.

**Comment by davidhealey** [comment] 2024-11-08 00:09
> > > > > Every single thing I have scanned to this point has started with a zero, and none of them work.
> > > > 
> > > > 
> > > > In what way did they not work?
> > > 
> > > 
> > > [#867 (comment)](https://github.com/davidhealey/waistline/issues/867#issuecomment-2461119065)
> > 
> > 
> > So these are items that are already in your foodlist and show a barcode in the food editor window?
> 
> Yes.

Can you show me a screenshot of one of the items with a 0 that doesn't work, and one that does?

**Comment by terminalmage** [comment] 2024-11-08 00:22
> > > > > > Every single thing I have scanned to this point has started with a zero, and none of them work.
> > > > > 
> > > > > 
> > > > > In what way did they not work?
> > > > 
> > > > 
> > > > [#867 (comment)](https://github.com/davidhealey/waistline/issues/867#issuecomment-2461119065)
> > > 
> > > 
> > > So these are items that are already in your foodlist and show a barcode in the food editor window?
> > 
> > 
> > Yes.
> 
> Can you show me a screenshot of one of the items with a 0 that doesn't work, and one that does?

[Works](https://github.com/user-attachments/assets/62425b7d-33d7-4e07-ae5d-949af007078e)

[Does not work](https://github.com/user-attachments/assets/9d9e71e6-a13f-4850-be74-cfda1b9af641)

**Comment by davidhealey** [comment] 2024-11-08 00:23
Can you show me one that begins with 0 that works?

**Comment by terminalmage** [comment] 2024-11-08 00:33
Literally everything else that I have scanned and saved into my local database begins with a zero, and none of them work. So I am unfortunately unable to provide an example of one beginning in zero which works.

If you are able to provide an example UPC code beginning in 0 which works, I can use one a barcode generator tool to turn it into a barcode that I can test.

It may indeed not be as simple as the UPC beginning with 0, but so far the only two things that I have scanned which do not start with a 0 are the only two that are properly selected from my local database when scanned.

**Comment by davidhealey** [comment] 2024-11-08 00:41
> I've actually now scanned two items beginning in zero and they both work.

So what did you mean here?

**Comment by terminalmage** [comment] 2024-11-08 00:46
That was a mistake, sorry for the confusion. I went back and edited that post. What I meant to say there was that I have now scanned two items that _do not_ begin with a zero and they are the only ones properly identified from the local database.

**Comment by davidhealey** [comment] 2024-11-08 00:47
Ah ok, well then it does indeed sound like you've found a bug. It certainly needs looking into anyway.

**Comment by EmilJunker** [comment] 2024-11-08 05:18
I get it now. Sorry for being so dismissive about this at first, this has actually been a known issue for a long time, but I kind of forgot about it. This is not a bug in Waistline. The barcode scanner plugin returns barcodes incorrectly if they begin with multiple leading zeros. There is an open issue for this problem: #701

To fix this problem, we need to make some changes in the way Waistline matches barcodes with items in the local database, e.g. ignore leading zeros.

**Comment by terminalmage** [comment] 2024-11-08 13:11
I have scanned items in my database with more than one leading zero. But if I remove all the leading zeroes and search Open Food Facts it still returns the correct item. So I assume that's how it's getting into the DB with the leading zeroes.

**Comment by terminalmage** [comment] 2024-11-08 14:15
Have a look at https://github.com/davidhealey/waistline/pull/868

Note: my editor is configured to remove trailing whitespace, so some of the lines in the diff have whitespace-only changes.

I built an APK using the docker image and confirmed this fixes the bug, but in order to do it I had to remove the query from `getAll()`. I'm open to more efficient solutions, if you all can think of them.

**Closed** 2024-11-24 14:35 UTC
Labels: bug
