### ISSUE TITLE
Dates keep reseting and changing

### ISSUE THREAD

**Issue by fitjova** [davidhealey/waistline#52] opened 2018-09-04 15:53 UTC
I'm having an issue on my  device running android  8.1 where the default day in the diary is never the day it currently is. It will often reset to the day before or the day before that.  

I can manually select today's date,  but after I add the food or go back to the diary later in the day to add more it defaults to a different day(sometimes with todays food added into yesterday's date).  

As a side note I'm super excited to see an open source calorie tracker out here. This app is simple, clean, and doesn't nag me to subscribe to their annual service while Im trying to input foods.

**Comment by davidhealey** [comment] 2018-09-04 16:08
This is a strange bug. What phone are you using? And which version of Android (I know you said 8.1 but is it a custom rom?) Also what version of Waistline?

**Comment by jingofett** [comment] 2018-09-05 07:06
Having this same issue on a LG G3 LineageOS 14.1. Using version 2.2.3 of the app

**Comment by davidhealey** [comment] 2018-09-05 11:44
I'm on LineageOS 14.1 too but I haven't come across this bug yet. Does it happen every time you use the app or is it random? Is it something that you could catch on video?

**Comment by fitjova** [comment] 2018-09-05 16:52
I'm on lineage os 15.1.
Here is a video 
https://gfycat.com/NaturalThriftyBordercollie

**Comment by davidhealey** [comment] 2018-09-05 17:40
Thank you, very helpful. Did this happen in any previous versions?

**Comment by Lense** [comment] 2018-09-07 17:43
The same thing is happening for me consistently. Don't know if it happened in previous versions since I just installed the app. I can try an older version if it would help.

Version 2.2.3 of app from google play store. Nexus 6P running Lineage 15.1-2018-0903-NIGHTLY-angler.

**Comment by davidhealey** [comment] 2018-09-07 19:50
Yes, please try an older version and let me know, that will be very helpful in finding the cause of this issue.

**Comment by Lense** [comment] 2018-09-07 23:03
Still happens in 2.1.0

If there's a specific older version you want me to try, lmk.

**Comment by davidhealey** [comment] 2018-09-08 08:46
Could you try 2.0.0 as well, that was the earliest version with the current system. It is starting to sound like this is a problem that's been there since v2, in which case I'm not able to reproduce it on my device. I'll have to get hold of some other devices so I can duplicate the problem but in the meantime I can try some things and you guys can test it.

**Comment by Lense** [comment] 2018-09-09 02:14
Still happens in debug 2.0.0 build.

**Comment by davidhealey** [comment] 2018-09-09 08:37
Thanks for confirming, that means it's been there for a while which implies the problem isn't widespread. So I shall start poking around the date handling when I'm putting together the next update and see if I can find something that looks like it could be causing this issue.

**Comment by Mitlik** [comment] 2018-09-09 14:01
I can confirm this bug on Android 8.0.0 (Sprint Samsung Galaxy S7) through the past 3 versions released on f-droid (currently 2.2.3).

**Comment by davidhealey** [comment] 2018-09-09 14:02
Hi guys, I've had a thought about this. I'm in the UK and my phone uses the date format dd/mm/yyyy, I notice in the GIF that was posted the date was in mm/dd/yyyy format. 

Are all of you using this date format, with the month first?

**Comment by Mitlik** [comment] 2018-09-09 14:05
Yes, using US default format (mm/dd/yyyy) here.

**Comment by davidhealey** [comment] 2018-09-09 14:13
I just tested changing the date format on my phone to US but I still can't reproduce the issue :( could you try changing to UK and seeing if the issue is resolved?

**Comment by davidhealey** [comment] 2018-09-09 14:34
Darn, oh well it was worth a try. I'll keep thinking and eventually it will get fixed

**Comment by Mitlik** [comment] 2018-09-09 14:38
I just noticed your comment about the date arrows. I haven't used them because "next date" doesn't work. 

When I use "previous date" and then add a food the date still changes. If I navigate back and forth enough eventually the added item appears in the diary.

**Comment by davidhealey** [comment] 2018-09-09 14:43
Oh that's strange. Javascript dates are a pain in the butt in general so it's not too surprising that this part of the app has some bugs, just wish they were easier to nail down. I'll get there.

**Comment by davidhealey** [comment] 2018-09-10 11:42
Ok I've made some changes to the date system, there is a debug build available here - https://github.com/davidhealey/waistline/tree/v2.3/platforms/android/app/build/outputs/apk/debug

Be warned however that installing this build may overwrite your existing install and delete current your data.

**Comment by Mitlik** [comment] 2018-09-10 12:13
I'm having issues installing apks not from an app store (it happened when I tried installing another apk as well so I'm pretty sure it's my issue). So while I would love to help test this build, I am running into difficulties.

If anyone is willing to trouble shoot this with me:
*  running the stock samsung image for galaxy s7
*  enabled firefox and my files to install unknown apps
*  after opening the apk it displays a a progress bar then ends by saying app not installed

If there are already enough testers I can wait until the new version hits f-droid.

**Comment by Lense** [comment] 2018-09-12 00:27
@davidhealey That debug apk seems to have some new bugs (like going back to statistics page whiile trying to add food to diary) that [git master](https://github.com/davidhealey/waistline/commit/03ec67c7d6cc9ee0721f48a0d75ac0c0f0f53509) doesn't have, so I'm just going to focus on master.

git master has some improvements and some new bugs:

### bugs

- Diary opens to the day before the current date
- When I select a date through the picker, it actually goes to 2 days before then

### fixed

- The back/forward arrows seem to work
- Adding foods goes back to the date that was open before.



@Mitlik That can happen when the previous version is not completely uninstalled. You can try installing through `adb install` to see more debug output. For me, `adb uninstall com.waist.line` fixed it.

**Comment by Mitlik** [comment] 2018-09-12 11:49
I've confirmed the behavior reported by lense, and i see the same improvements and issues. Including returning to home page after adding item to food list while trying to make a diary entry. The food list doesn't seem to save in the debug apk either. But those might be fixed in master.

Thanks @lense for the install tip.

**Comment by davidhealey** [comment] 2018-09-12 12:13
Thanks guys. Are these issues in the latest release - https://github.com/davidhealey/waistline/releases/tag/2.3.0 ?

**Comment by Mitlik** [comment] 2018-09-12 12:46
Installed the new linked rev:
*  Diary still opens to yesterday.
*  Date selector still opens two days prior to the selection

Will have to test out other noted issues later.

**Comment by davidhealey** [comment] 2018-09-12 12:57
Darn,I'm sure this is something to do with location but when I set my phone to US I still can't reproduce the issue. I'll have to try something else.

**Comment by davidhealey** [comment] 2018-09-12 13:45
> @davidhealey That debug apk seems to have some new bugs (like going back to statistics page whiile trying to add food to diary) that [git master](https://github.com/davidhealey/waistline/commit/03ec67c7d6cc9ee0721f48a0d75ac0c0f0f53509) doesn't have, so I'm just going to focus on master.
> 
> git master has some improvements and some new bugs:
> ### bugs
> 
>     * Diary opens to the day before the current date
> 
>     * When I select a date through the picker, it actually goes to 2 days before then

Ok I changed all of my phone settings to US and restarted my phone and now I can recreate these two bugs. So the next step is to fix it. Hopefully it won't take long and I'll have a new release today.

**Comment by Mitlik** [comment] 2018-09-12 13:46
Brain wave: the diary opening to yesterday issue might be linked to the statistics page not loading information for the current day.

I tried switching back to English UK for language and the locale still didn't seem to make a difference.

**Comment by davidhealey** [comment] 2018-09-12 13:46
> Brain wave: the diary opening to yesterday issue might be linked to the statistics page not loading information for the current day.
> 
> I tried switching back to English UK for language and the locale still didn't seem to make a difference.

I didn't know there was an issue with the statistics page. Please make a new github issue for it and I'll fix it.

**Comment by davidhealey** [comment] 2018-09-12 19:54
Hi Guys, I've been working on this all day, Javascript dates are horrible! Anyway I think I have something that might work. I've created a new branch for this and there is a debug build [here](https://github.com/davidhealey/waistline/tree/dateFix/platforms/android/app/build/outputs/apk/debug). Please give it a try, the usual warnings about data loss etc. when running a test build apply so use at your own risk.

**Comment by davidhealey** [comment] 2018-09-12 20:48
Yippie! I'll wait for some others to confirm before I mark this as fixed but as long as no other issues come up I think we're there! The alert box was something I was using for testing the stats page and forgot to take it out before pushing the apk. I'll remove it before release.

**Comment by davidhealey** [comment] 2018-09-14 19:41
I've just pushed this through as a release, let's see if it I got it right :)

**Comment by davidhealey** [comment] 2018-09-16 14:12
Hi guys, 

The last build had some new bugs and I'm not 100% certain the date issue was sorted. I've done some refactoring and made some significant under-the-hood changes and I'm hoping I've caught all these date bugs now. I've pushed a new release, if you could test and report back I'd be very grateful. I'm going to push the release to Play now so if you prefer you'll be able to download it from there soon.

**Comment by Mitlik** [comment] 2018-09-21 16:19
I see v2.3.3 finally hit f-droid.

I've been using the v2.3.1 build you had in the thread until the update percolated through. I had so little data in the app that I had been nuking my history while testing various builds. Now I have enough data to see more of the reporting features. I'll export data and reinstall from f-droid this weekend.

**Comment by davidhealey** [comment] 2018-09-21 16:35
There is a bug with food selection in 2.3.3 (I wish they'd gone straight to 2.3.4 but it's an automated system). It's actually a bug I thought I'd fixed a few version back so I'm not sure how it reappeared. Basically if you have two food items with the same brand in your list, selecting one of them will select the one nearest to the top of the list. It's very annoying but is fixed in 2.3.4 which will hopefully be on F-Droid soon.

**Comment by Mitlik** [comment] 2018-09-21 18:10
Thanks for the heads up, I'll switch to 2.3.4 instead and wait for f-droid
to release that (or better) before switching back to a repo install.

**Comment by davidhealey** [comment] 2018-10-07 21:06
> Thanks for the heads up, I'll switch to 2.3.4 instead and wait for f-droid to release that (or better) before switching back to a repo install.

Did you try out 2.3.4? and are you still experiencing the dates issue?

**Comment by davidhealey** [comment] 2018-10-18 22:10
Is anyone still experiencing this issue or can I close this one now?

**Comment by Mitlik** [comment] 2018-10-19 11:09
Fell out of using the app for a bit while I tried to figure out why import wouldn't work (I'll open an issue with findings). Been using 2.3.4 and it's pretty solid for dates. I do notice that sometimes the diary loads to the wrong date still, it's probably a UTC thing. But, entries to the diary seem to go against the correct day always so I'd say it went from major bug to very minir. I haven't tried 2.3.5 yet...

**Comment by corngood** [comment] 2018-10-25 02:08
> sometimes the diary loads to the wrong date still

Just started using the app today (2.3.7 from fdroid), and I noticed this.  I am UTC-4 I think, and it seemed to default to tomorrow starting around UTC midnight, so it's probably just using the UTC date?

**Comment by davidhealey** [comment] 2018-10-25 09:47
Thanks for reporting this. It looks like javascript dates strike again! It uses UTC + the timezone offset, but it never seems to work properly across all timezones.

Here's the exact code from the diary screen:
`diary.date.getTimezoneOffset() > 0 ? diary.date.setMinutes(diary.date.getTimezoneOffset()) : diary.date.setMinutes(-diary.date.getTimezoneOffset());`

**Comment by Mitlik** [comment] 2018-10-28 13:31
Can confirm it UTC-5

**Comment by corngood** [comment] 2018-11-11 04:31
@davidhealey  As far as I can tell, `new Date()` is returning local time, so I don't think the app should be taking timezone into account.  I removed all those adjustments:

```js
diff --git a/platforms/android/app/src/main/assets/www/activities/diary/js/diary.js b/platforms/android/app/src/main/assets/www/activities/diary/js/diary.js
index 5772ad16..39e14265 100755
--- a/platforms/android/app/src/main/assets/www/activities/diary/js/diary.js
+++ b/platforms/android/app/src/main/assets/www/activities/diary/js/diary.js
@@ -181,7 +181,6 @@ var diary = {
       if (diary.date == undefined)
       {
         diary.date = new Date();
-        diary.date.getTimezoneOffset() > 0 ? diary.date.setMinutes(diary.date.getTimezoneOffset()) : diary.date.setMinutes(-diary.date.getTimezoneOffset());
       }
 
       var categories = JSON.parse(app.storage.getItem("meal-names")); //User defined meal names are used as category names
@@ -284,7 +283,6 @@ $(document).on("show", "#diary-page", function(e){
   if (diary.date == undefined)
   {
     diary.date = new Date();
-    diary.date.getTimezoneOffset() > 0 ? diary.date.setMinutes(diary.date.getTimezoneOffset()) : diary.date.setMinutes(-diary.date.getTimezoneOffset());
   }
 
   diary.updateDisplayedDate();
@@ -365,7 +363,6 @@ $(document).on("keyup change", "#edit-diary-item #quantity", function(e){
 //Change date
 $(document).on("change", "#diary-page #date", function(e){
   diary.date = new Date($("#diary-page #date").val()); //Set diary object date
-  diary.date.getTimezoneOffset() > 0 ? diary.date.setMinutes(diary.date.getTimezoneOffset()) : diary.date.setMinutes(-diary.date.getTimezoneOffset());
   diary.populate();
 });
```

And it seemed to fix the problem for me.  I tried it in the emulator with a couple of different timezones.

I printed the date and I got this: `Sat Nov 10 2018 22:16:59 GMT-0600 (CST)`.  Node and firefox both print the current time in UTC...

**Comment by davidhealey** [comment] 2018-11-11 10:18
If that's the solution then I could kiss you! I'll try it out myself when I have some free time to work on Waistline (probably in a week or two).

**Comment by corngood** [comment] 2018-11-11 21:36
I don't think I'd bother switching to text.  Text dates would probably be more work and just as fragile as date objects.  As long as everything's well defined I think it's fine to use date objects in the DB.

I need to read up on the js Date object a bit more before I suggest anything detailed.

Does anything currently use the time of day stored in the diary?  I can imagine some interesting uses of it, like a graph of calories throughout the day, or auto assigning meals, but it could be really tricky to get right when the user can change timezones.

**Comment by davidhealey** [comment] 2018-11-11 22:14
No the time isn't used. In fact a few versions ago I had it set up so that the date would always be midnight in the hope it would prevent these date issues but it didn't make much difference.

**Comment by corngood** [comment] 2018-11-12 00:50
I tried to go through all the places dates are used and make sure it's all using UTC, see: 

https://github.com/corngood/waistline/commit/b4be6306188f655f3f4b8cdf78524e8b613c8f7d

I think it's still going to need a database migration, because some diary entries weren't being added to the current UTC day.  I'll look at that next, and make a PR after I deal with that and do a bit more testing.

**Comment by corngood** [comment] 2018-11-12 03:54
Here's what I have now with the database migration:

https://github.com/corngood/waistline/commit/813ac6b5c5c8e001a2c7474e1430e57cb27053d2#diff-43855e499c8b9132a189abd85dfccf80R97

I still have some concerns:

- diary entries will still be now always be added at midnight (maybe not a problem, but a change)

- migration will always negate the current timezone (probably the best we can do without some sort of notification/UI), will DST be a problem?

- migration never happens when importing the db, so export/import won't work across this change

**Comment by davidhealey** [comment] 2018-11-12 10:58
Thanks, that looks like a very workable solution and I like the simple migration function. I don't think the import/export will be an issue as apparently that feature is buggy and since I haven't had many people reporting it I get the feeling it's not being used much :p 

DST might be a problem. If we are using UTC is there any reason to set everything to midnight?

**Comment by Mitlik** [comment] 2018-11-12 12:02
Some thoughts on the related issues from someone using Waistline as their sole tracker...

I've used the import/export feature while trying out different debug builds and when I felt the need to factory reset my phone. The only bug I've noticed is the need to tap import multiple times (3-5ish) to get it to register. But continuity of data is an important feature to me. And I'll probably use it again when I migrate devices (need to get something I can run Lineage on).

I have enough data entered into Waistline that I would be disappointed to loose it. But, given that it exports to json, I'd at least have a way to recreate data. So it wouldn't hinder the tweaks I'm attempting too much.

I don't see having meal times as important. Sometimes I don't get to enter things until well after eating. Statistics by meal, I think,  would be more telling than by timestamp.

**Comment by davidhealey** [comment] 2018-11-12 12:35
Thanks for your input Mitlik, in that case I think the migration function should be called when importing old data

**Comment by corngood** [comment] 2018-11-12 16:57
As for the DST thing, this change shouldn't make it any worse, but the time change may cause some items to move between days.  So depending on when you upgrade your DB you may get different results.

**Closed** 2018-11-12 17:12 UTC
Labels: bug

**Comment by pyramid3d** [comment] 2019-02-10 03:09
Thanks for this useful app! Great job so far!

I am still having issues in version 2.3.7 (my TZ is UTC+8). At noon local time the diary starts displaying the next day by default.

Usually when dealing with dates, you keep the internal format in DB and code in UTC, and adjust it for display based on user TZ (for some of the problems discussed above like entries moving between dates when changing time zones) and preferred formatting (please do allow using global/international ISO date format YYYY-MM-DD).

For the issue at hand (opening diary in wrong date), actually the solution is much simpler: just use local time for default dairy date.

**Comment by davidhealey** [comment] 2019-02-10 12:44
The date issue was fixed (at least there have been no more complaints about it) in version 2.3.8 but the latest version is 2.4.2

**Comment by pyramid3d** [comment] 2019-02-10 23:51
Aw. It seems that my local f-droid repo was outdated when I installed waistline a week ago. Will test the latest version. Thumbs up!
