### ISSUE TITLE
Feature Request: Convert Category Foods to meal/recipe. 

### ISSUE THREAD

**Issue by tetricky** [davidhealey/waistline#761] opened 2023-09-30 18:40 UTC
I make my lunch,  by adding things (could be foods+recipes) as I prepare them to "Lunch" in the diary.

Then two things can happen:

1. I like it. I want to convert it to a recipe for future use.
2. Turns out that's too much (food, or calories). I'll call it several servings and have one now, one another time. 

In both these cases adjusting measurements today, and duplicating them for the next time,  is awkward. It's not a recipe yet,  or a meal.... but if it was I could meet those use cases easily.

Would it be possible to convert a diary category into a meal or recipe?

**Comment by EmilJunker** [comment] 2023-09-30 21:13
Duplicate of #547

**Closed** 2023-09-30 21:15 UTC

**Comment by tetricky** [comment] 2023-10-17 07:19
Can I just confirm that this isn't completed, as in it can be done in waistline. I still can't do it, or something like it.

It's completed in the sense it's not going to be done?

**Comment by davidhealey** [comment] 2023-10-17 09:56
Hi,

This was closed because as Emil posted above, it's a duplicate.
