### ISSUE TITLE
filtering in food item list stops working

### ISSUE THREAD

**Issue by corngood** [davidhealey/waistline#89] opened 2018-11-10 03:16 UTC
I'm using 2.3.7.

Some time today, the food item list stopped filtering when I enter text into the search box.  If I remove all user data and start a new food list it works.  In that case the list refreshes (check boxes flicker, and it filters) on every key press.  

With my full food items list (~80 items) the only time the list updates is when I delete the last character from the search box.  I can enter any text, but nothing happens to the list until I delete all of it.  When I delete the last character, the order of the items sometimes changes and duplicate items occasionally show up.  Filtering on recipes still works.

I tried clearing the cache.

I tried reinstalling the app and restoring data with titanium backup.

I tried removing some recently added items from the food list.

None of those things changed the behaviour.

I wanted to try restoring from an export, but nothing happens when I click the import button.

Do you think it would be useful to look in the ADB log?

**Comment by davidhealey** [comment] 2018-11-10 10:00
Hi,

This sounds like a strange one. Do any of your food items have unusual characters in their name?

The import not working is a big problem. I haven't tested it for a while so I'll check it out.

Yes a look at the log might reveal the source of the problem.

**Comment by corngood** [comment] 2018-11-10 13:35
Here's what I get in logcat each time I enter a character into the search box:

```
11-10 09:24:22.190 31218 31218 D SystemWebChromeClient: file:///android_asset/www/activities/food-list/js/food-list.js: Line 56 : Uncaught TypeError: Cannot read property 'match' of undefined
11-10 09:24:22.190 31218 31218 I chromium: [INFO:CONSOLE(56)] "Uncaught TypeError: Cannot read property 'match' of undefined", source: file:///android_asset/www/activities/food-list/js/food-list.js (56)
```

I thought about food items with special characters. I tried deleting the items I had recently added, but it didn't help.  I still think it's a possibility.

I'll get myself set up so I can build and test this on a simulator.

**Comment by davidhealey** [comment] 2018-11-10 14:12
Well that pinpoints the problem. I'll have to see if I can recreate it, it's weird that it was working and now it isn't. I suspect it's not a problem with the search box as such but something going wrong with the list of foods, like an unescaped character or a blank entry. I'm really busy at the moment but I'll try and get around to looking into this soon.

**Comment by corngood** [comment] 2018-11-10 19:34
Ok, I got waistline building and running on the emulator.  Turns out 'import data' actually works if you double click it.  ¯\_(ツ)_/¯

I guess it's probably still a bug, but at least that should let me import my data into the emulator.

**Comment by davidhealey** [comment] 2018-11-10 22:16
Ah that's interesting, i must have put the wrong action in

**Comment by davidhealey** [comment] 2018-11-11 10:15
Good catch. It'll be good if you can find out how it was caused and I'll also try and introduce some safe guards in the search box code if it finds an undefined value.

**Comment by davidhealey** [comment] 2018-11-25 23:46
Was this issue resolved?

**Comment by corngood** [comment] 2018-11-26 00:32
No, I haven't gone out of my way to reproduce it, but it hasn't happened to me since.  I suspect it might be a timing thing around editing food items.  Like if you submit during an asynchronous load or something?

**Comment by davidhealey** [comment] 2018-11-26 00:36
Ok, I'll leave this issue open for now then and I'll have a go at reproducing it at some point. Glad it seems like an edge case though.

**Comment by davidhealey** [comment] 2018-12-23 01:39
I noticed sometimes when searching for food I get a console message 

el.name is undefined

This could perhaps be related

**Comment by davidhealey** [comment] 2018-12-27 16:40
I fixed the el.name issue. I'm going to close this thread now, reopen it if the problem is repeatable :)

**Closed by davidhealey** 2018-12-27 16:40 UTC
Labels: bug
