### ISSUE TITLE
Labels on foods and meals

### ISSUE THREAD

**Issue by NK308** [davidhealey/waistline#408] opened 2021-11-21 01:41 UTC
It would be nice, if there was a way to filter entries in the lists of meals and foods, to avoid searching.

While custom labels probably would be best, a use case would be "ingredients" (for foods, rarely used outside of recipes) and "ready" (for food which is already portioned in a useful way, like a chocolate bar, something I buy in my university cantina (which has nutrition values online) or a pretzel I buy on my way home and estimate google it's estimated nutrition once. Useful labels for food could be things like "breakfast", "dinner" or "launch".

As soon, as the lists grow, this should save lots of time and be way faster then any search function, as long as the filters can be applied by a few finger taps.

A popup dialog while adding new foods (no matter, of manually or by barcode), to fastly apply already known labels, should also speed things up.

**Comment by EmilJunker** [comment] 2021-11-21 12:09
This is a duplicate of #328.

When I have some more time, I might look into ways to implement this. Unless somebody else wants to do it.

**Closed** 2021-12-17 12:39 UTC
