### ISSUE TITLE
bug: Unable to add foods with 0 calories to Diary

### ISSUE THREAD

**Issue by mlaradji** [davidhealey/waistline#33] opened 2018-08-05 18:29 UTC
When trying to add a food that has 0 in its Calories field, the Android app returns the following message: "Alert: Please complete all required fields." The error is avoided if Calories is changed to a positive (and non-zero) value.

**Comment by davidhealey** [comment] 2018-08-05 20:10
That's not a bug. The app is a calorie counter, why would you want to record a food that doesn't contain any calories?

**Comment by mlaradji** [comment] 2018-08-05 22:33
That's true, and if one only cares about macro-nutrients, there really is no point to adding a 0 calorie food. However, if one is keeping track of other nutrients, such as vitamins or salts, being able to add 0 calorie foods (for instance, multivitamin tablets) is helpful. Of course, this bug can be very easily bypassed by setting the calorie count to 1 or some small fraction instead of 0 when entering the food.

**Comment by davidhealey** [comment] 2018-08-05 22:48
Now that I think about it is strange that it doesn't accept 0 as a value. When I do a round of bug fixes I'll see if it's inherent in the system or if it's something I can make to work without much trouble.

**Comment by davidhealey** [comment] 2018-08-24 23:16
This is fixed now and will be available in the next update

**Closed by davidhealey** 2018-08-24 23:16 UTC
Labels: bug
