### ISSUE TITLE
Bug: Fails to detect internet availability

### ISSUE THREAD

**Issue by Blechpirat** [davidhealey/waistline#208] opened 2020-05-29 11:18 UTC
When Waistline was running in the background for a while (lineageOS 16.0 with micro-G) using the barcode scanner tells me that there is no internet available. Restarting the app solves that problem.

BTW: Great app, thank you, love using it!

**Comment by davidhealey** [comment] 2020-05-29 11:27
Thanks for the report, I'll add it to the list.

**Comment by davidhealey** [comment] 2021-03-26 23:20
I haven't been able to recreate this, do you have the steps to reproduce it reliably?

**Comment by davidhealey** [comment] 2021-06-04 23:45
I'm closing this issue since I can't reproduce it and therefore can't confirm any fixes I attempt.

**Closed by davidhealey** 2021-06-04 23:45 UTC
Labels: bug
