### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by faan11** [davidhealey/waistline#276] opened 2021-07-28 16:36 UTC
I tried the last version (v3.0) and i found that only the menu is translated. The rest is written in English language.
I'm using Android 10.
![image](https://user-images.githubusercontent.com/763700/127361664-8986ce94-76fd-4316-9e47-bb0d3028443a.png)
![image](https://user-images.githubusercontent.com/763700/127361687-abf111d5-b5f1-483d-a52c-0bdc9c1751da.png)

**Comment by davidhealey** [comment] 2021-07-28 16:37
Translations are added by the community, if you notice specific strings are missing from the source code let me know, but I don't handle individual languages.

**Comment by jfaltis** [comment] 2021-07-28 16:46
@davidhealey 

Did you merge the Crowdin translation branch? I added German translations via Crowdin but only the menu is translated as @faan11 described, despite that I translated all other strings too.

**Comment by davidhealey** [comment] 2021-07-28 16:50
> @davidhealey
> 
> Did you merge the Crowdin translation branch? I added German translations via Crowdin but only the menu is translated as @faan11 described, despite that I translated all other strings too.

V3.0.0 has a new schema for the language files, so locales for the old version need to be updated to be compatible. If your German translation for V3.0.0 or the previous release?

**Comment by faan11** [comment] 2021-07-28 17:08
I translated it 3 days ago, https://github.com/davidhealey/waistline/pull/272
Which schema I should follow to translate the application?

**Comment by davidhealey** [comment] 2021-07-28 17:14
@faan11 That's the correct one.

As you can see, some strings are missing from the Settings section. I'll need to add these to the template file (locale-en.json).

>   "settings": {
    "title": "Impostazioni",
    "needs-restart": "Riavvia l' applicazione per applicare le modifiche.",
    "theme": {
      "title": "Tema",
      "dark": "Modalità dark",
      "animations": "Disabilita le animazioni dell' interfaccia",
      "start-page": "Inizio pagina"
    },

**Comment by faan11** [comment] 2021-07-28 17:19
Ok let us now when the file locale-en.json is ready

**Comment by jfaltis** [comment] 2021-07-28 17:52
I translated it like 3 months ago, so I think it should also be version 3.0.0. I don't know if I am overlooking something but I think the https://github.com/davidhealey/waistline/tree/l10n_master2 branch needs to merged into master so the new translations are in the release.

**Comment by davidhealey** [comment] 2021-07-28 17:54
@jfaltis I think you're right. I'll merge it into the master before the next build, thanks!

**Comment by davidhealey** [comment] 2021-07-28 22:14
I've just looked into this a bit further and it seems all the strings are actually there - so something else is the problem. I'll find out what it is and fix it.

**Comment by davidhealey** [comment] 2021-07-28 22:44
Ok I found the cause of the issue. I'll fix it soon, probably tomorrow.

**Comment by EmilJunker** [comment] 2021-07-29 16:38
I noticed a few things regarding the localization and since this issue is still open, I will just add a comment here. I hope that's ok.

Issue 1: The branch https://github.com/davidhealey/waistline/tree/l10n_master2 still includes the old locale files located at /www/locales and /www/locaes so every time you merge that branch into master, these files will be recreated. It's probably best to remove them from there.

Issue 2: I believe you should rethink the way you localized the title in the food editor:

https://github.com/davidhealey/waistline/blob/f785c5225c2aa39da901eb65ec0a4118eae50ee4/www/activities/foods-meals-recipes/js/food-editor.js#L224

I'm not sure if this works (grammatically) in other languages. At least I'm having some trouble translating it into German. And you definitely can't just remove the letter 's' from the string to make it singular because this will interfere with other languages. For example, German "Lebensmittel" becomes "Lebenmittel" – that's not a word 😅

**Comment by davidhealey** [comment] 2021-07-29 16:43
@EmilJunker Duly noted. I'll adjust that and update the old locale branch, I think it makes sense to remove everything from there except the locale files.

**Comment by EmilJunker** [comment] 2021-07-29 18:03
One more thing: The link to request a USDA API key is also localized, but there are two problems with this.

https://github.com/davidhealey/waistline/blob/f785c5225c2aa39da901eb65ec0a4118eae50ee4/www/activities/settings/views/integration.html#L545

Problem 1: The source code references the string "settings.integration.usda-note-1" but in the locale files it's called "settings.integration.usera-note-1".

Problem 2: The fix you implemented (for issue #269) isn't yet reflected in the locale files.

**Comment by davidhealey** [comment] 2021-08-01 00:27
@EmilJunker 

This should fix the localization issues.

[app-release.zip](https://github.com/davidhealey/waistline/files/6911970/app-release.zip)

**Comment by EmilJunker** [comment] 2021-08-01 08:18
Yes, the localization is working now. But I noticed a few strings that aren't localized. Here's a (hopefully complete) list:

- the error message "no data" in the Diary (appears when requesting a pie chart for a day with no entries)
- the search box placeholder text "search" on the foods list page
- the string "show in statistics" in the Goals editor
- the string "show thumbnails" in diary settings
- the options "by last used" and "alphabeticallly" in foods/meals/recipes settings
- the string "preferred search language" in integrations settings
- the placeholder texts "your username" and "your password" of the input fields in OFF account settings
- the placeholder text "your API key" of the input field in USDA API settings
- the string "automatic backup" in import/export settings

Also, the USDA API link no longer works because it is now localized and the fix you implemented (for issue #269) isn't yet reflected in the locale files. You should either uncouple the link from the locale files or update it in the locale-en.json file.

**Comment by EmilJunker** [comment] 2021-08-01 10:56
Also, importing and exporting no longer works in the version you uploaded. I guess there is an issue with the localized error/success messages, but I don't know for sure.

**Comment by davidhealey** [comment] 2021-08-01 16:18
@EmilJunker 

USDA link is fixed now, I did as you suggested and removed it from the localization since the URL is the same in all languages. 

All of those missing localized strings plus a couple of others have been added.

I've improved the efficiency of the localization system. Previously it was re-reading the localization file on every reload, now it just does it once when the app is first opened. The automatic localization (handled by jquery localize) is now bypassed completely for English since this is the default and there is no need to relocalize these strings. This might give a slight performance boost on some devices when using English.

Importing/Exporting is fixed too. I'd switched my local branch to merge the locales branch, when I switched back to the master I had some issues and had to reinstall some Cordova plugins, I missed the Device plugin and this was causing the import/export to not work.

Assuming no major bugs in this version I'll push a new release soon.

[app-release.zip](https://github.com/davidhealey/waistline/files/6912968/app-release.zip)

**Comment by EmilJunker** [comment] 2021-08-02 07:41
@davidhealey 

Looks good. Importing/Exporting is working again and I didn't notice any bugs.

For some reason, the locale strings on [Crowdin](https://crowdin.com/project/waistline) are now split among two files. I don't know why this happened and I don't think it's a big problem, but it is a bit confusing. Maybe you can look into it...

In any event, I think you should wait a bit (at least a week) before pushing the next release so contributors have time to translate the new strings. Also, when you merge the l10n_master3 into master, you should check which languages aren't translated by then (currently Bulgarian, French and Swedish are all 0% translated) and remove them from the preferred language dropdown for the time being.

**Comment by davidhealey** [comment] 2021-08-02 10:44
> For some reason, the locale strings on [Crowdin](https://crowdin.com/project/waistline) are now split among two files. I don't know why this happened and I don't think it's a big problem, but it is a bit confusing. Maybe you can look into it...

@yarons Any ideas?

**Comment by yarons** [comment] 2021-08-02 11:05
The translations were pushed to the `main` branch while our working localization branch is actually `main_l10n3`.

We're also syncing the same file twice in the Crowdin integration, I can try and see if we can change it and if it's relevant to this case specifically.

**Comment by davidhealey** [comment] 2021-08-02 11:07
@yarons Thanks, that would be helpful, let me know if I need to do anything.

**Comment by yarons** [comment] 2021-08-02 11:10
Yup, we also need to remove `l10n_master2`, I removed `l10n_master` because it had no pending PRs but I can't remove the other one without closing the relevant PRs, should I just remove these?

**Comment by davidhealey** [comment] 2021-08-02 11:28
@yarons Yes it should be fine as I merged those changes locally already

**Comment by yarons** [comment] 2021-08-02 11:34
@davidhealey Done, what about all the other stale branches?

**Comment by davidhealey** [comment] 2021-08-02 11:36
@yarons If they're not causing any issues we can leave them

**Comment by yarons** [comment] 2021-08-02 12:21
Sure, I can't find the reason for the duplication in Crowdin but as lons as it's hidden I don't really care.

**Comment by EmilJunker** [comment] 2021-08-02 12:23
The `l10n_master3` branch is 4 commits behind `master`, maybe that's why?

**Comment by davidhealey** [comment] 2021-08-02 12:39
That branch will always be behind the master except for the locales which will always be ahead.

**Comment by EmilJunker** [comment] 2021-08-02 12:42
Yeah that makes sense. Then I'm out of ideas too.

**Comment by yarons** [comment] 2021-08-02 13:27
> Yes, the localization is working now. But I noticed a few strings that aren't localized. Here's a (hopefully complete) list:
@EmilJunker 

Can you try and switch to another language to see if it happens with other languages as well?

**Comment by EmilJunker** [comment] 2021-08-02 14:05
@yarons 
It affected all languages. But it should be fixed in the latest version from https://github.com/davidhealey/waistline/issues/276#issuecomment-890548095 that added a bunch of new locale strings.

To check if all the strings are now localized, we would need to add the translations first. I just completed the German translation on Crowdin, so if @davidhealey would merge it into master and publish a new APK, we could see if it really works.

Of course, the other languages need to be completed as well before the next release @huuhaa @faan11 @asdomingues

**Comment by faan11** [comment] 2021-08-07 09:04
ok i'll change and propose a pull request about the file it-locale.json  in the master branch.

**Comment by EmilJunker** [comment] 2021-08-07 09:07
@faan11 It's better and easier to add the translations via Crowdin: https://crowdin.com/project/waistline (you can sign in with your github account)

**Comment by faan11** [comment] 2021-08-07 09:29
ok I used Crowdin to add the new translations ( Android.app and locale json )

**Comment by davidhealey** [comment] 2021-08-07 21:29
This has been resolved now so I'll close this issue

**Closed by davidhealey** 2021-08-07 21:29 UTC
Labels: Missing Locale Strings
