### ISSUE TITLE
bug: deleting food In your diary deletes from food list

### ISSUE THREAD

**Issue by nutpantz** [davidhealey/waistline#9] opened 2018-05-26 19:31 UTC
Deleting food from your diary deletes all foods in that diary section from food list. Ie for breakfast you had "1 slice of bread" and "butter for bread". If you delete butter for bread both item's are deleted from the food list. (But 1 slice of  bread is still in diary)

**Comment by davidhealey** [comment] 2018-05-26 19:49
That doesn't happen for me. The version on FDroid isn't the latest version so this is possibly a bug that has already been fixed. If it still happens once the FDroid version gets updated then let me know and we can try and figure out the cause.

**Comment by nutpantz** [comment] 2018-05-26 20:02
Yep just grabbed 1.01 and it still does it. I'll try clearing data on the app and see if it is still doing it

**Comment by nutpantz** [comment] 2018-05-26 20:05
Yep made food list entries bread, cake, water. Added bread and cake to lunch. Then deleted cake now only water is left in food list.

**Comment by nutpantz** [comment] 2018-05-26 20:10
Ok might be related. Everything I add to food diary is removed from food list.. I added soup to breakfast and it is now gone from food list, added bread to lunch and it's going from the list.. Now sure what's going on.

**Comment by nutpantz** [comment] 2018-05-26 20:14
Yep seems to do it on 1.00 also..am I missing something here? I have a note 4 on android 6

**Comment by nutpantz** [comment] 2018-05-26 20:18
Yep. It seems that everything I add to my food diary disappears from the food list. So the bug title is just wrong. And it explains why I was confused..deleting has nothing to do with the issue.

**Comment by davidhealey** [comment] 2018-05-26 20:39
Can you make a video to demonstrate? I'm on Android 7 but I have tested on earlier versions. It will be interesting to see if others have this issue too.

**Comment by nutpantz** [comment] 2018-05-26 21:18
[20180526_135408.mp4.zip](https://github.com/davidhealey/waistline/files/2041964/20180526_135408.mp4.zip)


Here

**Comment by davidhealey** [comment] 2018-05-27 00:09
Also could you do a database export and send me the JSON file please?

**Comment by nutpantz** [comment] 2018-05-27 00:48
Got it from Google play (1.01)and from fdroid (1.00) running a Samsung Rom 6.01.

**Comment by davidhealey** [comment] 2018-05-27 09:40
I'll see if I can get hold of a similar device for testing. Can you send me the DB export file?

**Comment by nutpantz** [comment] 2018-05-27 14:03
It also does it on my my tablet that's also on factory marshmallow

**Comment by davidhealey** [comment] 2018-05-27 16:18
I didn't know it would even run on android 4.12! Can you do a database export and send me the file? this will help me to work out what the issue is.

**Comment by nutpantz** [comment] 2018-05-27 16:27
![waistline_export](https://user-images.githubusercontent.com/12160507/40588286-06712a1e-6190-11e8-8aa1-5df692f0b554.jpg)

Rename the extension..  (try2)

**Comment by davidhealey** [comment] 2018-05-27 17:04
Thanks, I imported your data into my phone and it showed up just fine in the app so the data is being saved properly but for some reason it's not displaying correctly on your devices. All I can think to do is test the app on more devices (whichever ones I can get hold of) until I can recreate the issue and then I can fix it.

**Comment by davidhealey** [comment] 2018-05-28 20:03
I have been able to generate and fix a similar bug which may be related, so when the next release comes out please test this again.

**Comment by AeliusSaionji** [comment] 2018-06-25 17:09
Still happening to me, latest FDroid version on stock pixel 2 Xl (Oreo).

Changes to the food list affect diary, but changes to the diary do not affect the food list. That is, adding a food from the diary is not remembered in the food list. Adding an item to the food list also added it to my breakfast in the diary.

**Comment by davidhealey** [comment] 2018-06-25 19:42
There has been some more updates but they haven't reached f-droid yet so this issue may be resolved.

**Comment by davidhealey** [comment] 2018-08-02 17:45
I've pushed the latest version to play and it should be on f-droid in the next few days. Please let me know if this issue is resolved

**Comment by davidhealey** [comment] 2018-08-16 15:31
I'm going to close this issue since no-one else has reported it with the new version, will reopen if someone finds it's still happening.

**Closed by davidhealey** 2018-08-16 15:31 UTC
