### ISSUE TITLE
Info on Data Sharing feature

### ISSUE THREAD

**Issue by schklom** [davidhealey/waistline#755] opened 2023-09-24 18:03 UTC
I love this app, but I can't seem to find any info on what `Data Sharing` sends, and how.

What data does it send? How often? In what format?
Is it similar to the Backup, but it sends the content of the backup it to a server?

Should I put the address to a WebDAV server (e.g. Nextcloud) there?

**Comment by EmilJunker** [comment] 2023-09-24 18:54
Duplicate of #723

**Closed** 2023-09-24 19:19 UTC
