### ISSUE TITLE
Rescanning bar code does not download updated info from OFF

### ISSUE THREAD

**Issue by prysm1** [davidhealey/waistline#288] opened 2021-08-04 16:43 UTC
This is probably a low priority
Deleting an item from the Food table and re-scanning of the bar code reuses the the old info.

Work around was to unlink the food entry and edit the information manually

**Comment by davidhealey** [comment] 2021-08-04 19:13
The intended behaviour is to first search the local database, if no result is found it then searches OFF. When item's are deleted they are not really deleted, they are marked as archived and hidden. This means they'll still show up in historic diary entries and statistics.

I could change the behaviour for archived items so it searches OFF first. What do you think?

**Comment by prysm1** [comment] 2021-08-04 19:49
The current behaviour is probably ok. As i am a very new user of waistline and not sure how everyone else is using it.
The reason i noticed this is, I find that some of the entries from OFF are not very good(my opinion only). So i tried to fix the entry  through the OFF website and then wanted to sync the new information. 

I think will just close this for now. I think the work around is good enough for me. Thanks for looking into this.

**Comment by davidhealey** [comment] 2021-08-04 19:56
I like the idea, it makes sense to me, so let's reopen this

**Comment by prysm1** [comment] 2021-08-04 20:11
ok. we would probably need a way to determine which data source is newer, otherwise it might clobber each others data.

**Comment by davidhealey** [comment] 2021-08-07 21:21
https://github.com/davidhealey/waistline/commit/49171a6a01a2882d63091227dba2e96b8a2576c5

**Closed by davidhealey** 2021-08-07 21:21 UTC
Labels: enhancement
