### ISSUE TITLE
Deselected item added to diary

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#467] opened 2022-01-29 02:44 UTC
To reproduce:

- Press `+` in diary.
- Select 2 items. [EDIT: Only manually created ones, not ones created by scanning a barcode.]
- Tap on one item and go back. (I used the OS's back button.)
- Deselect the item that you tapped on.
- Press `✔`.
- The app now incorrectly adds both items to the diary. This doesn't happen, if you deselect the item that you *didn't* tap on. (I have the quantity popup enabled, if that's relevant.)

**Comment by EmilJunker** [comment] 2022-01-29 11:15
I can't recreate this, neither on my phone nor in the browser. I'm using the latest version from the `master` branch, though. So maybe this bug has been fixed by a recent commit 🤔.

**Comment by EmilJunker** [comment] 2022-02-05 13:26
@h-h-h-h The latest release `3.2.3` is now available on F-Droid. Could you check if the issue is still reproducible in this version?

**Comment by h-h-h-h** [comment] 2022-02-05 17:07
The bug is still there in v3.2.3.

**Comment by EmilJunker** [comment] 2022-02-12 12:36
I still can't reproduce this. Anyone else having this problem?

@h-h-h-h Do you have UI animations enabled or disabled? Maybe that could be relevant?

**Comment by h-h-h-h** [comment] 2022-02-12 17:24
> Do you have UI animations enabled or disabled? Maybe that could be relevant?

I have animations disabled; but it also happens when I enable them.

However, I just found out that it only appears to happen with manually created items, not with those created by scanning a barcode.

**Comment by EmilJunker** [comment] 2022-02-12 22:16
When you deselect the item, does the selection count in the title bar change from `2 Selected` to `1 Selected`?

**Comment by h-h-h-h** [comment] 2022-03-02 03:22
The problem is still there in v3.3.0. There's another sequence of steps that may lead you closer to what's wrong with the code:

* (I have configured the app to sort foods according to what was used last.)
* Press `+` in diary.
* Select 1 predefined item.\* (You should probably always start from diary again.) Top text: "1 Selected".
  * \* Item prerequisites:
    * Manually create the following item: "A", "B", 100 ml, 123 kcal
    * If you don't press `✔`, but directly turn on linking and change 100 to 330 (ml), the problem will *continue* to happen with the item.
    * If you press `✔` and edit the item again to change 100 to 330 (linking will already be turned on), the problem will *cease* to happen with the item.
* Tap on the item and go back (I used the OS's back button). Top text: "1 Selected".
* Deselect the item. Top text: "1 Selected".
* Select the item again. Top text: "2 Selected".
* (More iterations of item peeking don't increase the counter any further.)
* Press `✔` and the item will be added to the diary twice.

**Closed** 2022-03-02 16:31 UTC
